# Generated by Django 5.1.3 on 2024-11-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='OurServices',
        ),
    ]
